#!/bin/bash

# --- Global Variables ---
DOTFILES_DIR=$HOME/dotfiles
BACKUP_DIR=$HOME/.config_backup_$(date +%Y%m%d_%H%M%S)

STOW_PACKAGES="fastfetch fonts gtk-3.0 gtk-4.0 hypr images kitty nvim rofi swaync wallust wallpapers waybar wlogout zsh"

# --- Backup Function ---
backup() {
    local target=$1
    if [ -e "$target" ] || [ -L "$target" ]; then
        echo "-> Backing up $target..."
        mv "$target" "$BACKUP_DIR/"
    fi
}

echo "Starting dotfiles installation..."

if [ ! -d "$DOTFILES_DIR" ]; then
    echo "ERROR: Dotfiles directory not found at $DOTFILES_DIR."
    exit 1
fi

if ! command -v stow &> /dev/null; then
    echo "ERROR: 'stow' is not installed. Please install it before continuing."
    exit 1
fi

# --- 1. Backup Phase ---
echo "--- Phase 1: Backing up existing configurations ---"
mkdir -p "$BACKUP_DIR"
echo "Old configurations (if found) will be moved to: $BACKUP_DIR"

backup "$HOME/.config/hypr"
backup "$HOME/.config/kitty"
backup "$HOME/.config/nvim"
backup "$HOME/.config/waybar"
backup "$HOME/.config/rofi"
backup "$HOME/.config/swaync"
backup "$HOME/.config/wlogout"
backup "$HOME/.config/wallust"
backup "$HOME/.config/gtk-3.0"
backup "$HOME/.config/gtk-4.0"
backup "$HOME/.local/share/fonts"
backup "$HOME/Pictures"
backup "$HOME/.config/fastfetch"
backup "$HOME/.local/share/fastfetch"         
backup "$HOME/.zshrc"
backup "$HOME/.p10k.zsh"
backup "$HOME/.oh-my-zsh"

echo "Backup complete."

# --- 2. Plugin Phase (Oh My Zsh) ---
echo "--- Phase 2: Installing External Plugins ---"
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Installing Oh My Zsh..."
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/oh-my-zsh/master/tools/install.sh)" "" --unattended
else
    echo "Oh My Zsh is already installed, skipping."
fi

echo "Installing Zsh Plugins"
ZSH_CUSTOM=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting || echo "Plugin syntax-highlighting already present."
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM}/themes/powerlevel10k || echo "Plugin powerlevel10k already present."
git clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM}/plugins/zsh-autosuggestions || echo "Plugin autosuggestions already present."

echo "Removing .zshrc generated by Oh My Zsh (to make room for ours)..."
rm -f "$HOME/.zshrc"

# --- 3. Linking Phase (Stow) ---
echo "--- Phase 3: Creating Symlinks (Stow) ---"
echo "Applying all packages: $STOW_PACKAGES"

cd "$DOTFILES_DIR"
stow -S $STOW_PACKAGES

if [ $? -ne 0 ]; then
    echo "ERROR: The 'stow' command failed."
    echo "Possible cause: unresolved conflicts (existing files)."
    echo "Check the files in $BACKUP_DIR and remove conflicts manually."
    exit 1
fi

echo "Symlinks created successfully."

# --- 4. Post-Installation Phase ---
echo "--- Phase 4: Post-Installation ---"

echo "Setting permissions for scripts..."
chmod +x "$HOME"/.config/hypr/scripts/*
chmod +x "$HOME"/.config/hypr/UserScripts/*
chmod +x "$HOME"/.config/hypr/initial-boot.sh

echo "Rebuilding font cache (fc-cache)..."
fc-cache -f -v

if [ -f /usr/bin/zsh ]; then
    echo "---"
    echo "WARNING: The script will now attempt to set Zsh as the default shell."
    echo "Enter the password for '$USER' (your login password) when prompted."
    echo "---"
    chsh -s /usr/bin/zsh
    if [ $? -ne 0 ]; then
        echo "ERROR: Shell change failed. Please run manually: chsh -s /usr/bin/zsh"
    fi
else
    echo "WARNING: /usr/bin/zsh not found."
fi

echo -e "\n--- INSTALLATION COMPLETE ---"
echo "Please, Log Out and Log In again to apply all changes."