
$battery = ~/.config/hypr/scripts/battery.sh 
$weather = ~/.config/hypr/scripts/weather.sh 
$location = ~/.config/hypr/scripts/location.sh

# --- BACKGROUND ---
background {
    monitor =
    path = ~/.config/hypr/hypr.png
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# --- GENERAL ---
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}


# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(255, 255, 255, 1)
    font_size = 100
    font_family = steelfish outline regular
    position = 0, 350
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 1)
    font_size = 28
    font_family = SF Pro Display Bold
    position = 0, 490
    halign = center
    valign = center
}


# Foreground Image
image {
    monitor =
    path = ~/.config/hypr/foreground-2.png
    size = 700
    border_size = 0
    rounding = 0
    rotate = 0
    reload_time = 0
    position = 0, -66
    halign = center
    valign = center
}

# USER Label
label {
    monitor =
    text =     $USER
    color = rgba(255, 255, 255, 1)
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    font_size = 18
    font_family = SF Pro Display Bold
    position = 0, -180
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99">Password</span></i>
    hide_input = false
    position = 0, -250
    halign = center
    valign = center
}

# Battery div
shape {
    monitor =
    size = 140, 80
    color = rgba(0, 75, 107, 1)
    rounding = 20
    rotate = 0
    position = -35, -100
    halign = right
    valign = top
    zindex = 1
}

# Battery Label
label {
    monitor =
    text = cmd[update:1000] echo -e "$($battery)"
    color = rgb(255, 255, 255)
    font_size = 25
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = -55, -115
    halign = right
    valign = top
    zindex = 5
}

# Weather div
shape {
    monitor =
    size = 210, 80
    color = rgb(240, 231, 219)
    rounding = 20
    rotate = 0
    position = -190, -100
    halign = right
    valign = top
    xray = false
    zindex = 1
}

# WEATHER Label
label {
    monitor =
    text = cmd[update:1000] echo "$($weather)"
    color = rgb(45, 48, 50)
    font_size = 10
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = -200, -115
    halign = right
    valign = top
    zindex = 5
}

# LOCATION Label
label {
    monitor =
    text = cmd[update:1000] echo "$($location)"
    color = rgb(45, 48, 50)
    font_size = 10
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = -255, -145
    halign = right
    valign = top
    zindex = 5
}