# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4F4F3
background         #1c1e1cff
cursor             #94AC9C

active_tab_foreground     #1c1e1cff
active_tab_background     #F4F4F3
inactive_tab_foreground   #F4F4F3
inactive_tab_background   #1C1E1C

active_border_color   #F4F4F3
inactive_border_color #1C1E1C
bell_border_color     #303A5C

color0      #424442
color1		#303A5C
color2		#284C33
color3		#585E75
color4		#888A92
color5		#B98674
color6		#A7A7A6
color7		#E7E7E6
color8		#A1A1A1
color9		#414D7B
color10		#356544
color11		#757E9B
color12		#B5B8C3
color13		#F7B39A
color14		#DFDFDD
color15		#E7E7E6
