# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F8F0EB
background         #1C1C1E
cursor             #979AB0

active_tab_foreground     #1C1C1E
active_tab_background     #F8F0EB
inactive_tab_foreground   #F8F0EB
inactive_tab_background   #1C1C1E

active_border_color   #F8F0EB
inactive_border_color #1C1C1E
bell_border_color     #13151D

color0      #424345
color1		#13151D
color2		#283358
color3		#284C33
color4		#B5453A
color5		#74707D
color6		#B09E95
color7		#EDE1DB
color8		#A69D99
color9		#191C26
color10		#364475
color11		#356544
color12		#F15C4D
color13		#9A95A7
color14		#EBD3C7
color15		#EDE1DB
