# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1C1E)
$foreground = rgb(F8F0EB)
$color0 = rgb(424345)
$color1 = rgb(13151D)
$color2 = rgb(283358)
$color3 = rgb(284C33)
$color4 = rgb(B5453A)
$color5 = rgb(74707D)
$color6 = rgb(B09E95)
$color7 = rgb(EDE1DB)
$color8 = rgb(A69D99)
$color9 = rgb(191C26)
$color10 = rgb(364475)
$color11 = rgb(356544)
$color12 = rgb(F15C4D)
$color13 = rgb(9A95A7)
$color14 = rgb(EBD3C7)
$color15 = rgb(EDE1DB)
