# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1E1C)
$foreground = rgb(F4F4F3)
$color0 = rgb(424442)
$color1 = rgb(303A5C)
$color2 = rgb(284C33)
$color3 = rgb(585E75)
$color4 = rgb(888A92)
$color5 = rgb(B98674)
$color6 = rgb(A7A7A6)
$color7 = rgb(E7E7E6)
$color8 = rgb(A1A1A1)
$color9 = rgb(414D7B)
$color10 = rgb(356544)
$color11 = rgb(757E9B)
$color12 = rgb(B5B8C3)
$color13 = rgb(F7B39A)
$color14 = rgb(DFDFDD)
$color15 = rgb(E7E7E6)
